### ISSUE TITLE
Unimath: \not shifts itself incorrectly

### ISSUE THREAD

**Issue by sp1ritCS** [NanoMichael/MicroTeX#115]
To reproduce, try:
```tex
$-5\not\in [0;11]$
```

The upper window is notekit w. unimath that has the broken `\not`, while the lower window is notekit with current clm 0.0.4, which looks  as expected. 
![Bildschirmfoto von 2022-03-14 14-10-28](https://user-images.githubusercontent.com/31540351/158218226-6dbb1e84-d7e2-4983-a3c2-a452a780e0b7.png)

---

what I've also noticed is, that the `'` for derivative functions looked far better in current clm than it does with unimath. Is this some kind of font issue?

**Comment by NanoMichael** [comment]
Seems `not` was not positioned correctly, I'll fix it later.

**Comment by NanoMichael** [comment]
fixed by #116, see https://nanomichael.github.io/MicroTeX/?tex=f(x)=ax\rightarrow%20f%27(x)=a\\0\not\in\{1,%202,%203\}\quad\sqrt{2}\not=1\quad\not\prod_{i=0}^\infty=0
