### ISSUE TITLE
\debug render error, first letter disappears

### ISSUE THREAD

**Issue by PikachuHy** [NanoMichael/MicroTeX#118]
case 1
```
\debug abc
```

case 2
```
\debug 
abc

```

![image](https://user-images.githubusercontent.com/18223871/158965356-df9a1774-39de-4434-9529-05f5e624ee43.png)

**Comment by NanoMichael** [comment]
Well, `debug` takes one argument 😅 , so `\debug abc` treat `a` as its argument. The following options are valid:

- showonlychar: if only show the char-boxes' bounding box
-  boundcolor: the bounding boxes' color
- baselinecolor: the boxes' baseline color

Options are separated by comma `,`. And `undebug` takes no arguments.

Please check [this demo](https://nanomichael.github.io/MicroTeX/?tex=\debug{showonlychar=false,boundcolor=blue,baselinecolor=red}efg) out.

**Comment by PikachuHy** [comment]
ok. 
thanks.
