### ISSUE TITLE
Segfaults in equation with $ and \not.

### ISSUE THREAD

**Issue by sp1ritCS** [NanoMichael/MicroTeX#121]
The equation
```tex
$g\not$
```
is causing µTeX to segfault. I asume this is, because it attempts to render the `\not` onto the not visible dollar sign. Weirdly this only happens when there is a char infront of the `\not`. `$\not$` renders just fine ._.

See:
https://nanomichael.github.io/MicroTeX/?tex=$a\not$

**Comment by NanoMichael** [comment]
fixed by #122
