### ISSUE TITLE
openmath regression: \emptyset missing

### ISSUE THREAD

**Issue by sp1ritCS** [NanoMichael/MicroTeX#138]
MicroTeX does not provide the `\empyset` macro that cLaTeXMath used to provide (![Bildschirmfoto vom 2022-11-10 13-59-38](https://user-images.githubusercontent.com/31540351/201098021-ec93e75a-4132-4632-aadf-68dbd2e8dcb6.png)).
 
See https://nanomichael.github.io/MicroTeX/?tex=$\emptyset$

**Comment by NanoMichael** [comment]
Some like the symbol `\phi` 🤔 , I'll check it soon.

**Comment by sp1ritCS** [comment]
It should be more like `\not0` than `\phi`

**Comment by NanoMichael** [comment]
fixed by #150
