### ISSUE TITLE
Issues with optional parameters in \newcommand

### ISSUE THREAD

**Issue by ArcheCraft** [NanoMichael/MicroTeX#141]
[In this example](https://nanomichael.github.io/MicroTeX/?tex=%24%5Cnewcommand%7B%5Cplim%7D%5B1%5D%5Bn%5D%7B%5Clim%5Climits_%7B%231%5Cto%5Cinfty%7D%7D%24%0A%24%5Cplim%5Bx%5D%20a_n%24%0A%24%5Cplim%7Bx%7D%20a_n%24%0A%24%5Cplim%20a_n%24%0A)
```tex
$\newcommand{\plim}[1][n]{\lim\limits_{#1\to\infty}}$
$\plim[x] a_n$
$\plim{x} a_n$
$\plim a_n$
```

I would expect the `\plim` usage to not remove the next char after it.
It seems like the parser is having issues with commands with optional parameters.

**Comment by NanoMichael** [comment]
fixed by [4383f55](https://github.com/NanoMichael/MicroTeX/commit/4383f55bb2a23d7791a9ade68e27781393f9030f)
