### ISSUE TITLE
Another segfault

### ISSUE THREAD

**Issue by sp1ritCS** [NanoMichael/MicroTeX#146]
The equation
```tex
$=\text{Ker}\begin{pmatrix}{\tiny \begin{matrix}\lambda_1-\lambda_i\\&\lambda_1-\lambda_i\end{matrix}}\\&{\tiny \begin{matrix}\ddots\\&0\\&&0\\&&&0\\&&&&0\end{matrix}\\&&{\tiny \begin{matrix}\lambda_1-\lambda_i\\&\lambda_1-\lambda_i\end{matrix}}}$
```

causes MicroTeX to segfault. While this isn't valid TeX and should probably result in a parsing failure, it shouldn't cause whatever application links against MicroTeX to crash.

(Also occurs on clm)

I've tried fixing it, however the entire stack seems to be exlusively random garbage in gdb

**Comment by NanoMichael** [comment]
fixed by 97e4b5d.

See this [example](https://nanomichael.github.io/MicroTeX/?tex=%24%3D%5Ctext%7BKer%7D%5Cbegin%7Bpmatrix%7D%7B%5Ctiny%20%5Cbegin%7Bmatrix%7D%5Clambda_1-%5Clambda_i%5C%5C%26%5Clambda_1-%5Clambda_i%5Cend%7Bmatrix%7D%7D%5C%5C%26%7B%5Ctiny%20%5Cbegin%7Bmatrix%7D%5Cddots%5C%5C%260%5C%5C%26%260%5C%5C%26%26%260%5C%5C%26%26%26%260%5Cend%7Bmatrix%7D%5C%5C%26%26%7B%5Ctiny%20%5Cbegin%7Bmatrix%7D%5Clambda_1-%5Clambda_i%5C%5C%26%5Clambda_1-%5Clambda_i%5Cend%7Bmatrix%7D%7D%7D%24).

On XeLaTeX and LuaLaTeX, this code will result in an error. The best approach would be to inform the user that using it this way is incorrect, but for now let's leave it as is.

**Comment by sp1ritCS** [comment]
> fixed by 97e4b5d .

great. I think I had already found a working version that used matrices within the matrix (useful when you want to "box" a certain part of the matrix using \fbox.

But the most important thing about this was that the stack-smashing that happened won't occur anymore (at least in this case), given that with specifically crafted formula input you're likely to get arbitrary code execution, which seems *really* dangerous. Maybe one should look into fuzzing to check if there is more of that.

**Comment by NanoMichael** [comment]
> given that with specifically crafted formula input you're likely to get arbitrary code execution, which seems really dangerous

That's true. But currently it seems that this situation is still within a controllable range, so I don't think we need to worry too much about it right now.

**Comment by sp1ritCS** [comment]
> But currently it seems that this situation is still within a controllable range, so I don't think we need to worry too much about it right now.

I'm not actually sure it is 🙃 . On the one hand, I'm don't think anyone is currently rendering "untrusted" equations using clm/µTeX, however if someone were to do that, it'll likely be quite fatal. 

However, a very large majority of crashes logged by notekit are due to cLaTeXMath. Obv. a large chunk of them already shouldn't occur anymore once MicroTeX is released, as the most common segfaults are already fixed, but running a fuzzer over it ([~sp1ritCS:cLaTeXMath/fuzzer](https://github.com/sp1ritCS/cLaTeXMath/tree/fuzzer/test/fuzzer)) I found 600 (filtered to 100) crashes in a *very short* amount of time, so I'll look into fixing at least some of them.

**Comment by NanoMichael** [comment]
> > But currently it seems that this situation is still within a controllable range, so I don't think we need to worry too much about it right now.
> 
> I'm not actually sure it is upside_down_face . On the one hand, I'm don't think anyone is currently rendering "untrusted" equations using clm/µTeX, however if someone were to do that, it'll likely be quite fatal.
> 
> However, a very large majority of crashes logged by notekit are due to cLaTeXMath. Obv. a large chunk of them already shouldn't occur anymore once MicroTeX is released, as the most common segfaults are already fixed, but running a fuzzer over it ([~sp1ritCS:cLaTeXMath/fuzzer](https://github.com/sp1ritCS/cLaTeXMath/tree/fuzzer/test/fuzzer)) I found 600 (filtered to 100) crashes in a _very short_ amount of time, so I'll look into fixing at least some of them.

Wow, that's really scary... Are you willing to submit `fuzzer` test code to the openmath branch? I'd like to test it out as well.

**Comment by sp1ritCS** [comment]
closing this as it has been fixed
