### ISSUE TITLE
SKIA rendering not support HDPI

### ISSUE THREAD

**Issue by LiuPeiqiCN** [NanoMichael/MicroTeX#158]
![image](https://github.com/NanoMichael/MicroTeX/assets/7535781/647f9663-aae7-45cc-a822-b2c71833c61f)

When the `BUILD_SKIA` option is enabled, the rendering quality degrades significantly on high-DPI displays, leading to noticeable aliasing or jagged edges in the rendered graphics.

**Comment by NanoMichael** [comment]
Which branch (openmath/master) do you use?

**Comment by LiuPeiqiCN** [comment]
master currently.
I'm attempting to work with the "openmath" branch, but I'm unable to successfully compile it. Skia requires support for SkParagraph, which cannot be directly built using vcpkg. I'm still in the process of trying to compile it.
