### ISSUE TITLE
[Branch: openmath] Crash with array and \mathxx and malformed brackets

### ISSUE THREAD

**Issue by jokteur** [NanoMichael/MicroTeX#160]
Hi,

When having this example code,
```Latex
\begin{array}{l}
  \mathbf{
\end{array}
```
or 
```Latex
\begin{array}{l}
  \mathit{
\end{array}
```

or whatever `\mathxx{`, microtex on the openbranch makes a segmentation fault.
In particular, in `atom_font.cpp`, my debugger says that:
```C++
sptr<Box> FontStyleAtom::createBox(Env& env) {
  if (_nested) {
    _mathMode ? env.addMathFontStyle(_style) : env.addTextFontStyle(_style);
    auto box = _atom->createBox(env);
    _mathMode ? env.removeMathFontStyle(_style) : env.removeTextFontStyle(_style);
    return box;
  }
  return env.withFontStyle(_style, _mathMode, [&](Env& e) { return _atom->createBox(e); }); // _atom is nullptr
}
```
`_atom`  is nullptr. This happens will all fonts, XITS, Latin Modern, Fira and Gyre DejaVu. This really only happens in array mode, and this bug doesn't happen in the master branch.

**Comment by sp1ritCS** [comment]
Add a check if _atom is `null` and if it is replace it with `sptrOf<EmptyAtom>()`.

See https://github.com/NanoMichael/MicroTeX/commit/2d06b1b2e3d5d21d179e4894ed90c57b3c592cde

There are quite a lot of issues exactly like this in the codebase. See #154

**Comment by sp1ritCS** [comment]
> P.S. I currently don't have much time to matain this project (I was actually laid off 😿, I'm preparing for a job interview, it would be great if someone could offer me a job opportunity).

That sucks 😦. I obv. have little to no idea how the job market is in mainland China, but I wish you best of luck in finding something stable :).
Does this that the initial MicroTeX release is postponed for an indefinite amount of time, or do you have the time to do an initial release of it in its current state (maybe with the docs from #129 added)?

**Comment by jokteur** [comment]
I don't have an enormous amount of time, if I can take the time to get familiar with the codebase, I could happily help squashing some of the bugs in the openmath branch.

**Comment by sp1ritCS** [comment]
> I don't have an enormous amount of time, if I can take the time to get familiar with the codebase, I could happily help squashing some of the bugs in the openmath branch.

The *very large* majority of bugs are nullptr derefs that occur due to the parser reading trashy input, like the one you've found here. As I've said, practically all of them can be fixed by replacing the nullptr with a `sptrOf<EmptyAtom>()`, there are just quite a lot of them (see the archive I've posted in the fuzzer PR). In this case, adding something like
```cpp
_atom = _atom == nullptr ? sptrOf<EmptyAtom>() : _atom;
```
or
```cpp
if (_atom == nullptr)
	_atom = sptrOf<EmptyAtom>();
```
at the start of the function should fix this.

**Comment by jokteur** [comment]
Thanks, I will make a PR maybe in September when I have a bit the time.
This library is really useful, so I plan to give back however I can.
