### ISSUE TITLE
tinyxml2 not found

### ISSUE THREAD

**Issue by afalkenhahn** [NanoMichael/MicroTeX#170]
I'm trying to build MicroTeX with MSVC so I first built tinyxml2 like this:

```
mkdir build
cd build
cmake -G "NMake Makefiles" ..
nmake
```

This worked fine. So then I tried to build MicroTeX like this:

```
mkdir build
cd build
cmake -G "NMake Makefiles" -DCMAKE_PREFIX_PATH=c:/test/tinyxml2-10.0.0 ..
```

But it didn't work. I got this error message from CMake:

```
CMake Error at CMakeLists.txt:51 (find_package):
Found package configuration file:

C:/test/tinyxml2-10.0.0/cmake/tinyxml2-config.cmake

but it set tinyxml2_FOUND to FALSE so package "tinyxml2" is considered to
be NOT FOUND.  Reason given by package:

tinyxml2 `shared` libraries were requested but not found.
```

Can anybody tell me how to solve this? Thanks!

**Comment by sp1ritCS** [comment]
You shouldn't have this issue when using µTeX from the openmath branch

**Comment by afalkenhahn** [comment]
I'm was using the master branch but switching to the openmath branch indeed solved the issue. Thanks!
